### ISSUE TITLE
feat: support public inputs

### ISSUE THREAD

**Issue by enricobottazzi** [privacy-scaling-explorations/greco#17]
- [ ] Find a way for verifier to generate gamma from the proof transcript
- [x]  expose ais_at_gamma_assigned, ct0is_at_gamma_assigned, cyclo_at_gamma_assigned as public inputs
- [x] fix deps on halo2_lib

**Comment by mahmudsudo** [comment]
can i take on this ?

**Comment by enricobottazzi** [comment]
Yes!

**Comment by enricobottazzi** [comment]
- [ ] update benches
- [ ] update python script 
- [ ] update negative tests
